/*
 Lozano Ramirez Angel Ivan    1CM3     PE18041900
 Caratula
*/

void caratula(void)
  {
   printf("\n\n\n\t\t\tInstituto Polit‚cnico Nacional");
   printf("\n\n\t\t   Unidad Profesional Adolfo L¢pez Mateos");
   printf("\n\n\t\t\t\t Zacatenco");
   printf("\n\n\t   Escuela Superior de Ingenier¡a Mec nica y El‚ctrica");
   printf("\n\n\n\n \t\tIngenier¡a en Comunicaciones y Electr¢nica");
   printf("\n\n \t\t\t Academia de Computaci¢n");
   printf("\n\n\t\t       Fundamentos de programaci¢n");
   printf("\n\n\t\t\tLozano Ram¡rez Angel Iv n");
   printf("\n\n\t\t\t\t  1CM3");
   printf("\n\n\t\t\t       PE18041900");
  }